# Generated by Django 5.0.4 on 2025-11-23 17:53

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.FloatField(validators=[main_app.validators.RangeValidator(0.0, 10.0, 'The rating must be between 0.0 and 10.0')]),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_year',
            field=models.IntegerField(validators=[main_app.validators.ReleaseYearValidator(1990, 2023, 'The release year must be between 1990 and 2023')]),
        ),
    ]
