# Generated by Django 5.0.4 on 2025-10-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('equipment', models.CharField(max_length=20)),
                ('video_url', models.URLField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('is_favourite', models.BooleanField(default=False)),
            ],
        ),
    ]
