# Generated by Django 5.0.4 on 2025-10-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
