# Generated by Django 5.0.4 on 2025-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_exercise_calories_burned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
