# Generated by Django 5.0.4 on 2025-10-29 15:32

from django.db import migrations

def migrate_unique_brands(apps, schema_editor):
    Shoe = apps.get_model("main_app", "Shoes")
    UniqueBrands = apps.get_model("main_app", "UniqueBrands")

    unique_brands_names = Shoe.objects.values_list("brand", flat=True).distinct()
    for brand_name in unique_brands_names:
        UniqueBrands.objects.create(brand_name=brand_name)

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(migrate_unique_brands),
    ]
