# Generated by Django 5.2.7 on 2025-10-30 15:05

from django.db import migrations

def set_smartphone_price(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    for smartphone in Smartphone.objects.all():
        smartphone.price = len(smartphone.brand) * 120
        smartphone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_smartphone_price),
    ]
