# Generated by Django 5.2.7 on 2025-10-30 15:25

from django.db import migrations
from datetime import timedelta

def update_order_fields(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    for order in Order.objects.all():
        if order.status == "Pending":
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == "Completed":
            order.warranty = "24 months"
            order.save()
        elif order.status == "Cancelled":
            order.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [
        migrations.RunPython(update_order_fields),
    ]
